#!/bin/bash
CONTAINER=armgpu
/usr/bin/docker run -it --rm  \
  -h ${CONTAINER} \
  -u $(id -u):$(id -g) -e HOME=${HOME} -e USER=${USER} -v ${HOME}:${HOME} \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -v /etc/shadow:/etc/shadow:ro \
  -v /etc/sudoers:/etc/sudoers:ro \
  -v /etc/timezone:/etc/timezone:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -v $(pwd):/work -v /nfs:/nfs -v /tftpboot:/tftpboot \
  ${CONTAINER} $@
